# Define a shared environment block for all services
x-variables:
  environment: &common_env
    SPRING_PROFILES_ACTIVE: datadir,standalone
    GEOSERVER_DATA_DIR: /opt/app/data_directory
    GEOWEBCACHE_CACHE_DIR: /data/geowebcache

volumes:
  shared_data_directory:
    driver_opts:
      type: none
      o: bind
      device: $PWD/datadir
  geowebcache_data:

services:
  gwc:
    image: geoservercloud/geoserver-cloud-gwc:2.28.1.1
    user: "1064:1064"
    environment:
      <<: *common_env
      # Disable LDAP health check
      MANAGEMENT_HEALTH_LDAP_ENABLED: "false"
      SPRING_LDAP_EMBEDDED_VALIDATION_ENABLED: "false"
    volumes:
      - ./gscloud-config:/etc/geoserver
      - shared_data_directory:/opt/app/data_directory
      - geowebcache_data:/data/geowebcache
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
  geodatabase:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    ports:
      - "5432:5432"
    volumes:
      - ./db-entrypoint:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_messages=debug1"]

